name: Release
run-name: ${{ github.actor }} creating new release
on:
  push:
    tags:
      - 'v\d+'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          npm ci
           npx playwright install --with-deps
           npm run test-ci
           npm run e2e

      - uses: actions/upload-artifact@v3
        id: playwright-test-report
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        id: unit-test-report
        with:
          name: unit-test-report
          path: test-report.html
          retention-days: 30

      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build/
          retention-days: 30

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Create Release Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          URL: ${{ steps.deployment.outputs.page_url }}
          REPORT1: ${{ steps.unit-test-report.output.value }}
          REPORT2: ${{ steps.playwright-test-report.output.value }}
        with:
          filename: .github/release-template.md
          update_existing: true
          search_existing: all

      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          URL: ${{ steps.deployment.outputs.page_url }}
          REPORT1: ${{ steps.unit-test-report.output.value }}
          REPORT2: ${{ steps.playwright-test-report.output.value }}
        with:
          filename: .github/release-template.md
          update_existing: true
          search_existing: all

  deploy:
    needs:
      - test
      - release

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
